### ISSUE TITLE
Enhancement - Page Settings quick link

### ISSUE THREAD

**Issue by moorecreative** [nbrane/Dnn.Administration-Suite#12]
Getting to the Page Settings for the page you are viewing has become a two step process on the DNN Core control bar... this used to be easy to see and launch...

How about adding a link to the Page Settings within either the TOOLS section, or perhaps this could be a new section in the left control section... one for Page Settings and it would show the most common items that used to be present in the older advanced control panel such as:
- current page's skin
- current pages visibility
- current page's parent

just a thought to consider

**Comment by ohine** [comment]
Thanks for the feedback! Keep it coming!

The next build will include a 'settings' link under pages which will load the edit page dialog directly for the current page. Putting that action under tools wouldn't reduce the amount of clicks for the end user from it's current position (clicking pages, then clicking the current page). 

The only way I could see to make it quicker was to add it to the top level. However, I'm still not too sure I like the placement. It might just need a different icon selected. Hopefully v0.1.0 will be out today so you can kick the tires a bit.
