### ISSUE TITLE
Bug? Menus do not open, no click action in ribbon

### ISSUE THREAD

**Issue by moorecreative** [nbrane/Dnn.Administration-Suite#20]
I'll research a touch further but just now we updated from version 0.5 to 1.2 and it may be that a script file is cached and I'm still seeing a mix of the old/new together

but after install of the new, the left side menu does not have action to slide/open with links. You can click on the icons but nothing happens. Same thing with the top right ribbon and the settings, info and logout, etc, clicking on them has no effect.

DNN 7.4.2, running Admin Suite 1.2, also running nBrane page caching

**Comment by ohine** [comment]
Do you have any errors in the js console? It does sound like a caching problem for sure. It could also be an issue with webapi as I moved the main js into a webapi endpoint to handle localization. Page caching shouldn't be causing this unless you enabled authenticated user caching.

**Comment by ohine** [comment]
Can you try the latest build to see if this has been fixed. I had another report from fb of a similar issue and was able to track it down. 

https://ci.appveyor.com/api/buildjobs/m78ixnoymoghymcc/artifacts/install/nBrane.AdministrationSuite_00.01.03_Install.zip

**Comment by moorecreative** [comment]
I was able to do a little more troubleshooting and had Fred look at what the conflict might be.

We could see an error that says it wont execute the script. 
_`' Refused to execute script from '***/desktopmodules/nbrane/administrationsuite/api/controlpanel/loadjs?name=main&cdv=217' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. '`_

Googling the error I see some mention of a header ' X-Content-Type-Options: nosniff ' that might be triggering the issue. Maybe we can add something to the web.config to remove that header? I'm not sure if that is what the issue is though.

That said, I do know that we have some pretty specific edits in the web.config for security and caching headers, etc, so perhaps there's a conflict or something that we need to make less strict. We're using a version of the web.config mentioned here
(http://www.moorecreative.com/Articles/Detail/tabid/522/ArticleId/69/DNN-Google-Page-Speed-Insights.aspx)

**Comment by moorecreative** [comment]
Meanwhile, I tried out the 1.3 version of the Administration Suite and it did not make a difference.

Also, tried hitting the desktop modules js file directly when logged in and it loaded with content correctly...

**Comment by moorecreative** [comment]
Yes, to confirm, the updated 1.3 version definitely addressed the issue, we can close this thread/issue.

Thanks!
