### ISSUE TITLE
Users Management don't works with object qualifier

### ISSUE THREAD

**Issue by lepigocher** [nbrane/Dnn.Administration-Suite#22]
The Users Management panel display an error when the DNN instance use an object qualifier. That's because the Data class use SQLHelper from Microsoft.ApplicationBlock.Data instead of the DataProvider.Instance() from DotNetNuke.Data.

**Comment by ohine** [comment]
I've manually merged this fix with 2768e2adc5c1d12c30808a6fb1b3ade99941997b
